# ######################################################
## RGB Underglow

CONFIG_ZMK_RGB_UNDERGLOW=y

# Encender RGB automáticamente al inicio
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

# Efecto: 0=Solid, 1=Breathe, 2=Spectrum, 3=Swirl
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

# Apagar RGB cuando el teclado está inactivo
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Color inicial (Hue 0-359, Sat 0-100, Brt 0-100)
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=240
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50

# Incrementos al ajustar con teclas
CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=10
CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=10
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=10

# Vincular RGB con external power (necesario para alimentar LEDs)
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y

# ######################################################
## RGB Backlight
## ZMK doesn't support per-key backlighting. The only lighting code that works with RGB LEDs is the underglow code, hence the suggestion to add your backlight LEDs to be part of underglow
CONFIG_ZMK_BACKLIGHT=y
# CONFIG_ZMK_BACKLIGHT_BRT_STEP=20
# CONFIG_ZMK_BACKLIGHT_BRT_START=40
# CONFIG_ZMK_BACKLIGHT_ON_START=y
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=n
# CONFIG_ZMK_BACKLIGHT_AUTO_OFF_USB=n

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

# Enable ZMK Studio Support
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_KEYBOARD_NAME="5013r c0rn3"